version: '3.8'
services:
  parking-db:
    image: postgres:16.1
    container_name: parking-db
    ports:
      - "6432:5432"
    environment:
      - POSTGRES_DB=parking-db
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345