version: '3.8'
services:
  parking-db:
    image: postgres:16.1
    container_name: parking-db
    ports:
      - "6432:5432"
    environment:
      - POSTGRES_DB=parking-db
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345

  parking-service:
    build: .
    container_name: parking-service
    ports:
      - "8080:8080"
    depends_on:
      - parking-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://parking-db:5432/parking-db
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=12345