server.port: 8080
spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:6432/parking-db
    driver-class-name: org.postgresql.Driver
    username: dbuser
    password: 12345
